docs: maintainers meeting 2023-11-02
onebeyond/maintainers pull request #152
Opened 2023-11-02 16:56 UTC by inigomarquinez

## Description

Add maintainers meeting notes from 2023-11-02

2023-11-06 16:08 UTC, UlisesGascon requested changes

2023-11-06 16:08 UTC, UlisesGascon commented on .nvmrc
> +18
This can be removed as https://github.com/onebeyond/maintainers/pull/153 is merged :)

2023-11-06 16:08 UTC, UlisesGascon commented on docs/03-meetings/2023-11-02.md
> +* **recording:** [Link](<to be added>)
We can remove references for the video recording for now due technical issues with the Google Account. 

```suggestion
## Links 
```

2023-11-13 11:23 UTC, UlisesGascon commented on .nvmrc
> +18
Solved in [5fd2534](https://github.com/onebeyond/maintainers/pull/152/commits/5fd2534350621df0b93e5a47470a3863cf9f8d8a)

2023-11-28 10:58 UTC, inigomarquinez commented on .nvmrc
> +18
Thanks

2023-11-28 11:06 UTC, UlisesGascon approved these changes

2023-11-28 11:06 UTC, merged